import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: '../api/schema/schema.gql',
  documents: ['./**/*.vue', '../../packages/ui/**/*.vue'],
  emitLegacyCommonJSImports: false,
  generates: {
    'gql/': {
      preset: 'client',
      plugins: [
        {
          add: {
            content:
              '// This file is auto-generated by GraphQL Codegen. Do not edit manually.\n',
          },
        },
      ],
      config: {
        useTypeImports: true,
      },
    },
    'gql/types.generated.ts': {
      plugins: ['typescript'],
    },
  },
}

export default config
