/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "schemas": {
        "translated_input": {
            "lang_title": string;
            "text_title": string;
            "auto_title": string;
        };
        "components": {
            "name_tr": {
                "title": string;
            };
            "desc_tr": {
                "title": string;
            };
            "image_url": {
                "title": string;
            };
            "primary_material": {
                "title": string;
            };
            "materials": {
                "title": string;
                "item_title": string;
            };
        };
    };
    "stream": {
        "score_rating": {
            "POOR": string;
            "FAIR": string;
            "GOOD": string;
            "VERY_GOOD": string;
            "EXCELLENT": string;
            "UNKNOWN": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
