/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "schemas": {
        "components": {
            "name_tr": {
                "title": string;
            };
            "desc_tr": {
                "title": string;
            };
            "image_url": {
                "title": string;
            };
            "primary_material": {
                "title": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
