/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "schemas": {
        "translatedInput": {
            "langTitle": string;
            "textTitle": string;
            "autoTitle": string;
        };
        "components": {
            "nameTr": {
                "title": string;
            };
            "descTr": {
                "title": string;
            };
            "imageURL": {
                "title": string;
            };
            "primaryMaterial": {
                "title": string;
            };
            "materials": {
                "title": string;
                "item_title": string;
            };
        };
    };
    "stream": {
        "scoreRating": {
            "POOR": string;
            "FAIR": string;
            "GOOD": string;
            "VERY_GOOD": string;
            "EXCELLENT": string;
            "UNKNOWN": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
