import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: '../../apps/api/schema/schema.gql',
  documents: './app/**/*.vue',
  generates: {
    'app/gql/': {
      preset: 'client',
      plugins: [
        {
          add: {
            content: '// This file is auto-generated by GraphQL Codegen. Do not edit manually.\n',
          },
        },
      ],
      config: {
        useTypeImports: true,
      },
    },
    'app/gql/types.generated.ts': {
      plugins: ['typescript'],
    },
  },
}

export default config
