import { type CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: './schema/schema.gql',
  documents: ['src/**/*.ts'],
  generates: {
    './test/gql/': {
      preset: 'client-preset',
      plugins: [
        {
          add: {
            content: '// This file is auto-generated by GraphQL Codegen. Do not edit manually.\n',
          },
        },
      ],
      config: {
        useTypeImports: true,
      },
    },
    './test/gql/types.generated.ts': {
      plugins: ['typescript'],
    },
  },
  hooks: {
    afterOneFileWrite: ['pnpm exec oxlint --fix --quiet'],
  },
}

export default config
